name: VChest
main: io.github.nicknazari.VChest.VChest
version: 1
author: airpod_salesman
commands:
  vc:
    description: Virtual chest to store items safely.
    usage: /vchest 
    permission:
    permission-message: