name: VChestReloaded
main: io.github.nicknazari.VChestReloaded.VChestReloaded
version: 1
author: airpod_salesman
commands:
  vc:
    description: Virtual chest to store items safely.
    usage: /vc
  getinventories:
    description: Debug, display inventories hashmap.
    usage: /getinventories